- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/cars_controller.rb
- app/views/cars/index.html.erb
- app/views/cars/show.html.erb
- config/routes.rb
- test/controllers/cars_controller_test.rb
> Car show page

- app/controllers/cars_controller.rb
- app/views/cars/index.html.erb
- config/routes.rb
- test/controllers/cars_controller_test.rb
Hey guys, 
I have just implemented the first version of our user story
As a user I want see all the vinages cars.
Cheers
> show all pages

- app/views/cars/show.html.erb
add some nice details about our car...
> add car details on cars#show

- app/controllers/bookings_controller.rb
- app/controllers/cars_controller.rb
- app/views/cars/show.html.erb
- config/routes.rb
- db/seeds.rb
Guys,
I have updated our cars#show view
it now includes 
- Booking form - to create a new booking
- Booking Table - to see available booking (just to see that something is stored / temporary purpose)
We still have some open issues
- We need a starting date and end-date for booking --> change to db.schema / model required
Furthermore I have updated the seed.rb
with a second user and also show some codes ... just habe a look !
> update cars#show with booking-feature

- app/controllers/cars_controller.rb
Updated the car show with the right method to fix display issue.
> Update car show

- app/views/cars/index.html.erb
- app/views/cars/new.html.erb
- app/views/reviews/new.html.erb
- app/views/shared/_navbar.html.erb
I have added some litle cosmetics ... hope you like it
> add some nice little layout

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_searchform.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
I have just created the first draft for our landing page... nothing revolutionary.. but clean and simple.
I add a form where visitors / users can type in the city where they live in order to find a car nearby.
Any comments :-)
> add landing-page

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_searchbar.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
Hi, I did a new update of our landing page.
Search features is per default: shows all cars which are in db.
> add new landing page 2nd try

- app/controllers/application_controller.rb
Hi guys,
as I visitor I can see landing page, index page and show page without lbeeing logged in.
When I start booking I have to logged in.
> create the correct flow for vistor / user

- app/controllers/pages_controller.rb
- app/controllers/users_controller.rb
- app/views/pages/profile.html.erb
- app/views/shared/_navbar.html.erb
- app/views/users/show.html.erb
- config/routes.rb
Hi guys,
I have created a profile page for a current_user.
I also link it in the navbar.
> linking navbar & create profile page

- app/assets/stylesheets/config/_fonts.scss
- app/views/cars/show.html.erb
- app/views/pages/home.html.erb
Hi guys,
change font
add awsesome font
> Styling on landing page / show page

- app/controllers/bookings_controller.rb
- app/controllers/pages_controller.rb
- app/views/shared/_navbar.html.erb
- config/routes.rb
Hola mis amigos!
Booking list ready
> booking list and navbar booking

- app/views/pages/dashboard.html.erb
> dashboard html

- app/views/pages/home.html.erb
- app/views/pages/profile.html.erb
- db/seeds.rb
Updated marketing text and mission on the front page. 
Created a new design for the home page / Landing page
Corrected some typos
Made a beautiful seed for the demo with 12 cars from 4 different countries and all the specifications.
> Update marketing text

- app/controllers/bookings_controller.rb
- app/controllers/cars_controller.rb
- app/views/cars/create.html.erb
- app/views/cars/edit.html.erb
- app/views/cars/new.html.erb
- app/views/cars/show.html.erb
- app/views/layouts/application.html.erb
design : Homepage,...
content for homepage
Homepage , 2 divs added with content (Owner / Renter)
db update, view update, favicon, metadata
> design , content, db update, view update, favicon, metadata

- app/assets/stylesheets/components/_card.scss
- app/controllers/bookings_controller.rb
- app/views/cars/show.html.erb
Cars show page. New style :peru:
> new design cars show

- app/views/pages/dashboard.html.erb
Hi guys, we can add some reviews to the bookings
> add review feature

- app/views/pages/dashboard.html.erb
> review feature in place

- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
Hi, just some little styling on login pages
> style user / login / logout

- app/assets/stylesheets/components/_card.scss
- app/views/cars/index.html.erb
- app/views/cars/show.html.erb
fixes on pages on index / show - now ratio should be ok
> some fixes according images

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_map.scss
- app/controllers/cars_controller.rb
- app/views/cars/_info_window.html.erb
- app/views/cars/show.html.erb
> Revert "add map feature on showpage"

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_map.scss
- app/controllers/cars_controller.rb
- app/javascript/plugins/init_mapbox.js
- app/views/cars/_info_window.html.erb
- app/views/cars/show.html.erb
now we can display geo information on show page -
one issue: zoom level of cards... gonna fix that with ta
> Fix maps showpage

- app/views/cars/index.html.erb
- config/routes.rb
link image / fix car details on card
> fix image / link images
